version: "3.8"

services:
    mysqldb:
        image: mysql:5.7
        restart: always
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=achatdb
        ports:
            - 3306:3306
        volumes:
            - db:/var/lib/mysql

    app_achat_backend:
        depends_on:
            - mysqldb
        image: nassimbs/achat
        restart: always
        ports:
            - 8089:8089
        environment:
            SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/achatdb?useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null,
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "management.server.address" : "0.0.0.0",
        "management.endpoints.web.exposure.include" : "*",
        "management.endpoint.health.show-details" : "always"
      }'

        volumes:
            - .m2:/root/.m2
        stdin_open: true
        tty: true

    app_achat_frontend:
        build: nassimbs/crudtuto-Front
        restart: always
        ports:
            - 4200:4200
        volumes:
            - .:/app
        stdin_open: true
        tty: true

volumes:
    db: